# Generated by Django 5.0.6 on 2024-06-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="text",
            new_name="message",
        ),
    ]
