# Generated by Django 5.0.6 on 2024-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_rename_text_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
